Document: pam-propperpwnam
Title: Debian pam-propperpwnam Manual
Author: <insert document author here>
Abstract: This manual describes what pam-propperpwnam is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pam-propperpwnam/pam-propperpwnam.sgml.gz

Format: postscript
Files: /usr/share/doc/pam-propperpwnam/pam-propperpwnam.ps.gz

Format: text
Files: /usr/share/doc/pam-propperpwnam/pam-propperpwnam.text.gz

Format: HTML
Index: /usr/share/doc/pam-propperpwnam/html/index.html
Files: /usr/share/doc/pam-propperpwnam/html/*.html
